In [91]:
import numpy as np

In [92]:
# Function generates 10*10*10 array with random integers [0;9] 

def random_integers(low=0, high=9, elements=10, dimension=3):
    arr3d = np.random.randint(low, high=high, size=elements**dimension)
    return arr3d.reshape((elements,)*3)

In [93]:
vec = random_integers() # default 10*10*10 array with random integers [0;9]
vec.shape # shape of the array

(10, 10, 10)

In [94]:
# Function returns the maximum sum of columns and columns coordinates 

def max_sum_coord(vec, n):
    coordinates=[]
    all_sum=[]
    for matrix in xrange(n):
        for column in xrange(n):
            for row in xrange(n):
                # summing throught all mutually perpendicular 
                all_sum.append(sum(sum([vec[matrix,:,column],vec[matrix,row,:],vec[:,row,column]])))
                # coordinates appending
                coordinates.append([matrix,column,row])
                
    # maximum of sums
    max_index=all_sum.index(max(all_sum))
    return max(all_sum), coordinates[max_index]

In [95]:
n=vec.shape[0]
max_sum,coordinates=max_sum_coord(vec, n)

In [96]:
# Returns 3 perpendicular columns ( numpy arrays)  which sum is the maximum

def max_columns(vec, coordinates):
    matrix,column,row=coordinates[0],coordinates[1],coordinates[2]
    vectors = []
    return vec[matrix,:,column], vec[matrix,row,:], vec[:,row,column]

In [97]:
max_columns(vec, coordinates)

(array([4, 3, 7, 6, 8, 8, 6, 6, 5, 7]),
 array([7, 2, 4, 8, 3, 8, 6, 4, 5, 8]),
 array([6, 3, 8, 7, 6, 7, 8, 6, 4, 5]))

In [98]:
# Printing the Results:
def print_columns(vec, coordinates):
    matrix,column,row=coordinates[0],coordinates[1],coordinates[2]
    print "\n vec[%s,:,%s] : " % (matrix,column), vec[matrix,:,column]
    print "\n vec[%s,%s,:] :" % (matrix,row), vec[matrix,row,:]
    print "\n vec[:,%s,%s] : " % (row,column), vec[:,row,column]
def print_result():
    print "Max sum of Columns is: ", max_sum
    print "\n Columns are: \n", print_columns(vec, coordinates)

print_result()

Max sum of Columns is:  175

 Columns are: 

 vec[2,:,9] :  [4 3 7 6 8 8 6 6 5 7]

 vec[2,4,:] : [7 2 4 8 3 8 6 4 5 8]

 vec[:,4,9] :  [6 3 8 7 6 7 8 6 4 5]
None
